services:
  nginx:
    restart: always
    image: nginx:alpine
    ports:
      - 5443:443
    links:
      - registry:registry
    volumes:
      - ./certs:/etc/nginx/conf.d:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  registry:
    image: registry:2
    expose:
      - "5000"
      - "5001"
    volumes:
      - ./registry/config.yml:/etc/docker/registry/config.yml
      - ./certs:/certs
      - registry-volume:/var/lib/registry
  auth:
    image: cesanta/docker_auth
    command: "--v=2 --alsologtostderr /config/auth_config.yml"
    expose:
      - "5002"
    volumes:
      - ./certs:/certs
      - ./auth/config.yml:/config/auth_config.yml
  prometheus:
    image: prom/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.route-prefix=/
      - --web.external-url=/prometheus
    expose:
      - "9090"
    volumes:
      - ./prometheus:/etc/prometheus
volumes:
  registry-volume:
    external: true
