# A simple example. See reference.yml for explanation for explanation of all options.
#
#  auth:
#    token:
#      realm: "https://localhost:5443/auth"
#      service: "registry-server"
#      issuer: "registry-issuer"
#      rootcertbundle: "/certs/auth.crt"

server:
  addr: "0.0.0.0:5002"

token:
  issuer: "registry-issuer"  # Must match issuer in the Registry config.
  expiration: 900
  certificate: "/certs/auth.crt"
  key: "/certs/auth.key"

users:
  # Password is specified as a BCrypt hash. Use `htpasswd -nB USERNAME` to generate.
  "admin":
    password: "$2y$05$LO.vzwpWC5LZGqThvEfznu8qhb5SGqvBSWY1J3yZ4AxtMRZ3kN5jC"  # badmin
  "test":
    password: "$2y$05$WuwBasGDAgr.QCbGIjKJaep4dhxeai9gNZdmBnQXqpKly57oNutya"  # 123
  "": {}  # Allow anonymous (no "docker login") access.

acl:
  - match: {account: "admin"}
    actions: ["*"]
    comment: "Admin has full access to everything."
  - match: {account: "test"}
    actions: ["pull"]
    comment: "User \"test\" can pull stuff."
  - match: {account: ""}
    actions: ["pull"]
  # Access is denied by default.